In [3]:
import numpy as np
import pandas as pd
import math as m
import yfinance as yf

In [4]:
pip install yfinance


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


Reading one year data of NIFTY 50 Index price from 03/01/2022 to 03/01/2023

In [5]:
df = pd.read_csv("C:/Users/debas/Downloads/^NSEI (1).csv")
df.head(50)

Date          Open          High           Low         Close  \
0   2023-08-28  19298.349609  19366.849609  19249.699219  19306.050781   
1   2023-08-29  19374.849609  19377.900391  19309.099609  19342.650391   
2   2023-08-30  19433.449219  19452.800781  19334.750000  19347.449219   
3   2023-08-31  19375.550781  19388.199219  19223.650391  19253.800781   
4   2023-09-01  19258.150391  19458.550781  19255.699219  19435.300781   
5   2023-09-04  19525.050781  19545.150391  19432.849609  19528.800781   
6   2023-09-05  19564.650391  19587.050781  19525.750000  19574.900391   
7   2023-09-06  19581.199219  19636.449219  19491.500000  19611.050781   
8   2023-09-07  19598.650391  19737.000000  19550.050781  19727.050781   
9   2023-09-08  19774.800781  19867.150391  19727.050781  19819.949219   
10  2023-09-11  19890.000000  20008.150391  19865.349609  19996.349609   
11  2023-09-12  20110.150391  20110.349609  19914.650391  19993.199219   
12  2023-09-13  19989.500000  20096.900391  19944.099609  20070.000000   
13  2023-09-14  20127.949219  20167.650391  20043.449219  20103.099609   
14  2023-09-15  20156.449219  20222.449219  20129.699219  20192.349609   
15  2023-09-18  20155.949219  20195.349609  20115.699219  20133.300781   
16  2023-09-20  19980.750000  20050.650391  19878.849609  19901.400391   
17  2023-09-21  19840.550781  19848.750000  19709.949219  19742.349609   
18  2023-09-22  19744.849609  19798.650391  19657.500000  19674.250000   
19  2023-09-25  19678.199219  19734.150391  19601.550781  19674.550781   
20  2023-09-26  19682.800781  19699.349609  19637.449219  19664.699219   
21  2023-09-27  19637.050781  19730.699219  19554.000000  19716.449219   
22  2023-09-28  19761.800781  19766.650391  19492.099609  19523.550781   
23  2023-09-29  19581.199219  19726.250000  19551.050781  19638.300781   
24  2023-10-03  19622.400391  19623.199219  19479.650391  19528.750000   
25  2023-10-04  19446.300781  19457.800781  19333.599609  19436.099609   
26  2023-10-05  19521.849609  19576.949219  19487.300781  19545.750000   
27  2023-10-06  19621.199219  19675.750000  19589.400391  19653.500000   
28  2023-10-09  19539.449219  19588.949219  19480.500000  19512.349609   
29  2023-10-10  19565.599609  19717.800781  19565.449219  19689.849609   
30  2023-10-11  19767.000000  19839.199219  19756.949219  19811.349609   
31  2023-10-12  19822.699219  19843.300781  19772.650391  19794.000000   
32  2023-10-13  19654.550781  19805.400391  19635.300781  19751.050781   
33  2023-10-16  19737.250000  19781.300781  19691.849609  19731.750000   
34  2023-10-17  19843.199219  19849.750000  19775.650391  19811.500000   
35  2023-10-18  19820.449219  19840.949219  19659.949219  19671.099609   
36  2023-10-19  19545.199219  19681.800781  19512.349609  19624.699219   
37  2023-10-20  19542.150391  19593.800781  19518.699219  19542.650391   
38  2023-10-23  19521.599609  19556.849609  19257.849609  19281.750000   
39  2023-10-25  19286.449219  19347.300781  19074.150391  19122.150391   
40  2023-10-26  19027.250000  19041.699219  18837.849609  18857.250000   
41  2023-10-27  18928.750000  19076.150391  18926.650391  19047.250000   
42  2023-10-30  19053.400391  19158.500000  18940.000000  19140.900391   
43  2023-10-31  19232.949219  19233.699219  19056.449219  19079.599609   
44  2023-11-01  19064.050781  19096.050781  18973.699219  18989.150391   
45  2023-11-02  19120.000000  19175.250000  19064.150391  19133.250000   
46  2023-11-03  19241.000000  19276.250000  19210.900391  19230.599609   
47  2023-11-06  19345.849609  19423.000000  19309.699219  19411.750000   
48  2023-11-07  19404.050781  19423.500000  19329.099609  19406.699219   
49  2023-11-08  19449.599609  19464.400391  19401.500000  19443.500000   

       Adj Close  Volume  
0   19306.050781  248200  
1   19342.650391  307400  
2   19347.449219  233000  
3   19253.800781  562600  
4   19435.300781  333000  
5   19528.800781  296800  
6   19574.900391  256800  
7   19611.050781  2

VOLATILITY FUNCTION: This function is computed by calculating the percentage change of daily closing Prices and then computing the standard deviation of daily returns.

In [6]:
def volatility(df):
    df['volat'] = df['Adj Close'].pct_change()
    vol = df['volat'].std(ddof=0) * np.sqrt(252)
    return vol

In [7]:
volatility(df)

0.1331933674386044

In [8]:
df.head(50)

Date          Open          High           Low         Close  \
0   2023-08-28  19298.349609  19366.849609  19249.699219  19306.050781   
1   2023-08-29  19374.849609  19377.900391  19309.099609  19342.650391   
2   2023-08-30  19433.449219  19452.800781  19334.750000  19347.449219   
3   2023-08-31  19375.550781  19388.199219  19223.650391  19253.800781   
4   2023-09-01  19258.150391  19458.550781  19255.699219  19435.300781   
5   2023-09-04  19525.050781  19545.150391  19432.849609  19528.800781   
6   2023-09-05  19564.650391  19587.050781  19525.750000  19574.900391   
7   2023-09-06  19581.199219  19636.449219  19491.500000  19611.050781   
8   2023-09-07  19598.650391  19737.000000  19550.050781  19727.050781   
9   2023-09-08  19774.800781  19867.150391  19727.050781  19819.949219   
10  2023-09-11  19890.000000  20008.150391  19865.349609  19996.349609   
11  2023-09-12  20110.150391  20110.349609  19914.650391  19993.199219   
12  2023-09-13  19989.500000  20096.900391  19944.099609  20070.000000   
13  2023-09-14  20127.949219  20167.650391  20043.449219  20103.099609   
14  2023-09-15  20156.449219  20222.449219  20129.699219  20192.349609   
15  2023-09-18  20155.949219  20195.349609  20115.699219  20133.300781   
16  2023-09-20  19980.750000  20050.650391  19878.849609  19901.400391   
17  2023-09-21  19840.550781  19848.750000  19709.949219  19742.349609   
18  2023-09-22  19744.849609  19798.650391  19657.500000  19674.250000   
19  2023-09-25  19678.199219  19734.150391  19601.550781  19674.550781   
20  2023-09-26  19682.800781  19699.349609  19637.449219  19664.699219   
21  2023-09-27  19637.050781  19730.699219  19554.000000  19716.449219   
22  2023-09-28  19761.800781  19766.650391  19492.099609  19523.550781   
23  2023-09-29  19581.199219  19726.250000  19551.050781  19638.300781   
24  2023-10-03  19622.400391  19623.199219  19479.650391  19528.750000   
25  2023-10-04  19446.300781  19457.800781  19333.599609  19436.099609   
26  2023-10-05  19521.849609  19576.949219  19487.300781  19545.750000   
27  2023-10-06  19621.199219  19675.750000  19589.400391  19653.500000   
28  2023-10-09  19539.449219  19588.949219  19480.500000  19512.349609   
29  2023-10-10  19565.599609  19717.800781  19565.449219  19689.849609   
30  2023-10-11  19767.000000  19839.199219  19756.949219  19811.349609   
31  2023-10-12  19822.699219  19843.300781  19772.650391  19794.000000   
32  2023-10-13  19654.550781  19805.400391  19635.300781  19751.050781   
33  2023-10-16  19737.250000  19781.300781  19691.849609  19731.750000   
34  2023-10-17  19843.199219  19849.750000  19775.650391  19811.500000   
35  2023-10-18  19820.449219  19840.949219  19659.949219  19671.099609   
36  2023-10-19  19545.199219  19681.800781  19512.349609  19624.699219   
37  2023-10-20  19542.150391  19593.800781  19518.699219  19542.650391   
38  2023-10-23  19521.599609  19556.849609  19257.849609  19281.750000   
39  2023-10-25  19286.449219  19347.300781  19074.150391  19122.150391   
40  2023-10-26  19027.250000  19041.699219  18837.849609  18857.250000   
41  2023-10-27  18928.750000  19076.150391  18926.650391  19047.250000   
42  2023-10-30  19053.400391  19158.500000  18940.000000  19140.900391   
43  2023-10-31  19232.949219  19233.699219  19056.449219  19079.599609   
44  2023-11-01  19064.050781  19096.050781  18973.699219  18989.150391   
45  2023-11-02  19120.000000  19175.250000  19064.150391  19133.250000   
46  2023-11-03  19241.000000  19276.250000  19210.900391  19230.599609   
47  2023-11-06  19345.849609  19423.000000  19309.699219  19411.750000   
48  2023-11-07  19404.050781  19423.500000  19329.099609  19406.699219   
49  2023-11-08  19449.599609  19464.400391  19401.500000  19443.500000   

       Adj Close  Volume     volat  
0   19306.050781  248200       NaN  
1   19342.650391  307400  0.001896  
2   19347.449219  233000  0.000248  
3   19253.800781  562600 -0.004840  
4   19435.300781  333000  0.009427  
5   19528.800

MODEL ASSUMPTIONS AND VARIABLE NAMES:


*   Current stock price is: 𝑆
*   𝑇 is the Maturity time (taken as 200 days) of the Option, with 𝑁 number of periods(I calculate Option Price keeping N = 4,5,10)


*   d𝑡 is the time represented in each period
*   If the stock price goes up with a value U; such that: 𝑈 = 𝑒𝑥𝑝(𝜎 ∗ √𝛥𝑡) the new stock price value is: 𝑆u = 𝑆𝑜 ∗ 𝑈


*   If the stock price goes down by a value D; such that: 𝐷 = 𝑒𝑥𝑝(−𝜎 ∗ √𝛥𝑡) the new stock price value is: 𝑆𝑑 = 𝑆𝑜 ∗ D
*   The relationship between U and D is as follow: 𝑈 = 1/𝐷


*   The risk free interest rate, r, is taken as 6% p.a.










RISK NEUTRAL PROBABILITY

In [9]:
def RiskNeutralProbability(r,dt,v): # r: risk-free interest rate, dt = time duration of one period, v = volaitility
        u = np.exp(v*np.sqrt(dt))   # u: upfactor of spot price, d: down-factor of spot pticr
        d = 1/u
        rnp = (np.exp(r*dt)-d)/(u-d)
        return rnp

SPOT PRICE: I fetch the spot price of Yahoo Finance.

In [11]:
ticker = yf.Ticker('^NSEI')
df2 = ticker.history(period="1d")
S = df2["Close"]
S

Date
2024-08-28 00:00:00+05:30    25052.349609
Name: Close, dtype: float64

BINOMIAL TREE OF SPOT PRICE OF STOCK

In [12]:
def spot_tree(n,T,S,v): # n: no. of periods, T: Maturity Time of the Option (in years), S: Spot Price , v: volatility
    dt = T/n
    u = np.exp(v*np.sqrt(dt))
    d = 1/u
    price_tree = np.zeros((n+1, n+1))
    for j in range(n+1):
        for i in range(j+1):
            price_tree[i,j] = S*m.pow(d,i) * m.pow(u,j-i)
    return price_tree

In [13]:
days_in_year = 365
n = 4
t = 200/days_in_year
v = volatility(df)
Tree1 = np.array(spot_tree(n,t,S,v))
n = 5
Tree2 = np.array(spot_tree(n,t,S,v))
n = 10
Tree3 = np.array(spot_tree(n,t,S,v))


print("Binomial Tree of Spot Prices when no. of periods = 4")
print(Tree1.astype(int))
print("Binomial Tree of Spot Prices when no. of periods = 5")
print(Tree2.astype(int))
print("Binomial Tree of Spot Prices when no. of periods = 10")
print(Tree3.astype(int))

Binomial Tree of Spot Prices when no. of periods = 4
[[25052 26318 27648 29045 30513]
 [    0 23847 25052 26318 27648]
 [    0     0 22700 23847 25052]
 [    0     0     0 21608 22700]
 [    0     0     0     0 20568]]
Binomial Tree of Spot Prices when no. of periods = 5
[[25052 26181 27361 28595 29884 31231]
 [    0 23971 25052 26181 27361 28595]
 [    0     0 22937 23971 25052 26181]
 [    0     0     0 21948 22937 23971]
 [    0     0     0     0 21001 21948]
 [    0     0     0     0     0 20095]]
Binomial Tree of Spot Prices when no. of periods = 10
[[25052 25845 26664 27508 28379 29278 30205 31162 32149 33167 34217]
 [    0 24283 25052 25845 26664 27508 28379 29278 30205 31162 32149]
 [    0     0 23537 24283 25052 25845 26664 27508 28379 29278 30205]
 [    0     0     0 22815 23537 24283 25052 25845 26664 27508 28379]
 [    0     0     0     0 22114 22815 23537 24283 25052 25845 26664]
 [    0     0     0     0     0 21436 22114 22815 23537 24283 25052]
 [    0     0     0     0

BINOMIAL TREES FOR OPTION VALUES FOR CALL AND PUT OPTIONS

In [14]:
def Options_Tree(n, S, E, r, v, T, P_C):      # n: no. of periods, S: Spot Price, E: Exercise Price, r: risk-free rate
    dt = T/n                                 # T: Maturity Time of the Option (in years), v: volatility
    rnp = RiskNeutralProbability(r,dt,v)     # Put: if(Put=1) function computes Put Option tree, if(Put=0) function computes Call Option tree
    Spot_Tree = spot_tree(n,T,S,v)
    Option_Tree = np.zeros((n+1, n+1))

    for j in range(n+1, 0, -1):
        for i in range(j):
            if (P_C == 1):   #put option
                if(j == n+1):
                    Option_Tree[i,j-1] = max(E-Spot_Tree[i,j-1], 0)
                else:
                    Option_Tree[i,j-1] = m.exp(-r*dt)*(rnp*Option_Tree[i,j] + (1-rnp)*Option_Tree[i+1,j])
            if (P_C == 0):   #call option
                if (j == n + 1):
                    Option_Tree[i,j-1] = max(Spot_Tree[i,j-1]-E, 0)
                else:
                    Option_Tree[i,j-1] = m.exp(-r*dt) * (rnp*Option_Tree[i,j] + (1-rnp)*Option_Tree[i+1,j])
    return [Spot_Tree,Option_Tree]

In [15]:
N = 200 # Maturity Time of Option in Days
days_in_year = 365
E = S.item() #Taking Exerice Price equal to spot price
r = 0.06
T = N/days_in_year
v = volatility(df)
n = 4
P_C = 0
Spot_Tree,Call_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
P_C = 1
Spot_Tree,Put_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
print('No. of Periods: 4')
print('Spot Price Tree:\n',np.matrix(Spot_Tree.astype(int)))
print('Call Option Tree:\n',np.matrix(Call_Option_Tree.astype(int)))
print('Put Option Tree:\n',np.matrix(Put_Option_Tree.astype(int)))
print('\n')
n = 10
P_C = 0
Spot_Tree,Call_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
P_C = 1
Spot_Tree,Put_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
print('No. of Periods: 10')
print('Spot Price Tree:\n',np.matrix(Spot_Tree.astype(int)))
print('Call Option Tree:\n',np.matrix(Call_Option_Tree.astype(int)))
print('Put Option Tree:\n',np.matrix(Put_Option_Tree.astype(int)))

No. of Periods: 4
Spot Price Tree:
 [[25052 26318 27648 29045 30513]
 [    0 23847 25052 26318 27648]
 [    0     0 22700 23847 25052]
 [    0     0     0 21608 22700]
 [    0     0     0     0 20568]]
Call Option Tree:
 [[1366 2056 3004 4198 5460]
 [   0  472  833 1471 2595]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]]
Put Option Tree:
 [[ 556  180    0    0    0]
 [   0 1067  425    0    0]
 [   0    0 1943  999    0]
 [   0    0    0 3239 2352]
 [   0    0    0    0 4483]]


No. of Periods: 10
Spot Price Tree:
 [[25052 25845 26664 27508 28379 29278 30205 31162 32149 33167 34217]
 [    0 24283 25052 25845 26664 27508 28379 29278 30205 31162 32149]
 [    0     0 23537 24283 25052 25845 26664 27508 28379 29278 30205]
 [    0     0     0 22815 23537 24283 25052 25845 26664 27508 28379]
 [    0     0     0     0 22114 22815 23537 24283 25052 25845 26664]
 [    0     0     0     0     0 21436 22114 22815 23537 24283 25052]
 [    0     0     0     0 